version: '{build}'
skip_tags: true
clone_depth: 10
platform:
  - x86
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - master
os: Windows Server 2012
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\Program Files (x86)\Apache\Maven" )) {
        MkDir("C:\Program Files (x86)\Apache\Maven")
        Write-Host "Downloading Maven..."
        (new-object System.Net.WebClient).DownloadFile('http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip', 'C:\Program Files (x86)\Apache\Maven\bin.zip')
        Write-Host "Unzipping Maven..."
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\Program Files (x86)\Apache\Maven\bin.zip", "C:\Program Files (x86)\Apache\Maven")
      }
  - cmd: SET PATH=C:\Program Files (x86)\Apache\Maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -X -Dmaven.test.skip=true
test_script:
  - mvn clean install --batch-mode -Pqulice
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
on_finish:
  - mvn clean --batch-mode