/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_wkn_jni_AssemblerFunctions */

#ifndef _Included_ru_wkn_jni_AssemblerFunctions
#define _Included_ru_wkn_jni_AssemblerFunctions
#ifdef __cplusplus
extern "C" {
    #endif
    /*
     * Class:     ru_wkn_jni_AssemblerFunctions
     * Method:    dividingFunction
     * Signature: (DD)D
     */
    __declspec(dllexport) JNIEXPORT jdouble JNICALL Java_ru_wkn_jni_AssemblerFunctions_dividingFunction
      (JNIEnv *, jobject, jdouble, jdouble);

    /*
     * Class:     ru_wkn_jni_AssemblerFunctions
     * Method:    xorFunction
     * Signature: (II)I
     */
    __declspec(dllexport) JNIEXPORT jint JNICALL Java_ru_wkn_jni_AssemblerFunctions_xorFunction
      (JNIEnv *, jobject, jint, jint);

    #ifdef __cplusplus
}
#endif
#endif
