/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_wkn_javasm_AssemblerFunctions */

#ifndef _Included_ru_wkn_javasm_AssemblerFunctions
#define _Included_ru_wkn_javasm_AssemblerFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_wkn_javasm_AssemblerFunctions
 * Method:    dividingFunction
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ru_wkn_javasm_AssemblerFunctions_dividingFunction
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     ru_wkn_javasm_AssemblerFunctions
 * Method:    xorFunction
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ru_wkn_javasm_AssemblerFunctions_xorFunction
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
