package ru.wkn.views;

public enum WindowType {

    MAIN_WINDOW,
    ANALYZER_WINDOW,
    ASSEMBLER_MATH_WINDOW,
    FILE_DB_WINDOW,
    NETWORK_RESOURCE_WINDOW,
    SERVER_INFORMATION_WINDOW,
    NETWORK_ACCESS_WINDOW
}
